### ISSUE TITLE
Requires application to have ActiveRecord enabled

### ISSUE THREAD

**Issue by will-in-wi** [airbrake/airbrake-ruby#102]
If you have active record disabled:

```ruby
# Toward the top of application.rb
require 'rails'
# Pick the frameworks you want:
# require 'active_model/railtie'
# require 'active_job/railtie'
# require 'active_record/railtie'
require 'action_controller/railtie'
# require 'action_mailer/railtie'
require 'action_view/railtie'
require 'sprockets/railtie'
require 'rails/test_unit/railtie'
```

You get the following error when you start the server:

```uninitialized constant Airbrake::Rails::Railtie::ActiveRecord (NameError)```

This points at line 26 of railtie.rb, which looks like:

```ruby
app.config.middleware.insert_after(
  ActiveRecord::ConnectionAdapters::ConnectionManagement,
  'Airbrake::Rack::Middleware'
)
```

I'm using Airbrake-Ruby 1.4.4.

Thanks!

**Comment by kyrylo** [comment]
Thanks for the bug report. I'm going to close this in favour of https://github.com/airbrake/airbrake/issues/579 since this is the correct repository.
