### ISSUE TITLE
Adding to the 'params' area of airbrake.io when Airbrake.notify not explicitly called

### ISSUE THREAD

**Issue by hale** [airbrake/airbrake-ruby#112]
airbrake (5.3.0), airbrake-ruby (1.4.2), ruby 2.2.3p173

Passing custom params is straightforward when explicitly notifying Airbrake:`Airbrake.notify("Temp is too high", params: { max_temp: 300 }`

How can extra params be passed when Airbrake is notified implicitly e.g. from a failed request or failed job in Sidekiq / ActiveJob?

---

I gather from https://github.com/airbrake/airbrake/issues/528 that this might be possible using the `add_filter` API but I don't think `notice` exposes the exception object itself.

(Looking here - https://github.com/airbrake/airbrake-ruby/blob/e426a94fd90080d76b04ddecaa2448353a2f58fc/lib/airbrake-ruby/nested_exception.rb#L16 - we only get the class name, message and backtrace of exceptions. No way to access arbitrary attributes on the exception.)

e.g. 

```ruby
  class Error < StandardError
    attr_reader :params

    def initialize(params = {})
      @params = params
    end
  end

  # if it were possible to expose the exception object on `notice`:
  class AddCustomParamsFilter
    def call(notice)
      notice[:errors].each do |error|
        notice[:params].merge!(error[:type] => error[:exception].params)
      end
    end
  end
```

------

Stepping back a bit - what I'd like to do is define exception classes with custom attributes and have those attributes pass over to Airbrake. At the moment I'm including all the required information in the `#message`, which is messy and prevents the UI from deduping the errors properly.

**Comment by kyrylo** [comment]
You can access much more than what you pointed out. Check this: https://github.com/airbrake/airbrake-ruby#notice--notice

You could attach your info to `notice[:params]`.

Does this answer your question?

**Comment by kyrylo** [comment]
I think what you want is achievable with `add_filter`.

**Comment by hale** [comment]
I don't think so, but could be missing something - thanks for your help.

https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/notice.rb#L55

The initializer of Notice doesn't set `exception` and none of the keys in `modifiable_payload` contain it either. How would I pass the `params` object from the custom error example above using `add_filter`? (I referenced NestedException because it would be nice to include custom attributes for 'wrapped' exceptions as well)

---

One alternatie to `add_filter` would be to override `as_json` in ActiveJob jobs (cf. https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails/active_job.rb#L19) and do something similar for the other contexts where errors could be raised. 

This isn't very reliable though, I like the idea of using filters to ensure params are captured globally - if something like that is possible.

**Comment by kyrylo** [comment]
What kind of custom parameters would you like to attach? By default, we try to send all the available parameters. At the moment I am not quite sure why you need access to the exception object. You are correct, we don't expose it, but it's information is exposed as the `Notice` object, which contains parsed information. Thus, to add something to the parameters tab in the dashboard you would need the following filter:

```rb
Airbrake.add_filter do |notice|
  notice[:params][:your_param] = 'your value'
end
```

Wrapped exceptions are also parsed, and you can access their information with the same API:

```rb
Airbrake.add_filter do |notice|
  notice[:errors][0] #=> latest raised exception
  notice[:errors][1] #=> original exception
  notice[:errors][i] #=> so on
end
```

I think I would able to provide a better reply if I knew what exactly you would like to pass.

**Comment by hale** [comment]
> What kind of custom parameters would you like to attach? 

Here's an example of a custom error class that includes response information from Faraday:

```ruby
module MyLibrary
  class Error < StandardError
    attr_reader :params

    def initialize(params = {})
      @params = params
    end
  end

  class ConnectionError < Error
    def initialize(faraday_error, params = {})
      super(params.merge(faraday: {
        message: faraday_error.message,
        response: faraday_error.response
      }))
    end
  end
end
```

If the filter needs to be in the same scope as the info to pass, maybe something like this is the answer:

```ruby
module MyLibrary
  class Error < StandardError
    attr_reader :params

    def initialize(params = {})
      @params = params
      configure_airbrake
    end
    
    private
    
    def configure_airbrake
      Airbrake.add_filter do |notice|
        notice[:params][:my_library] = params
      end
    end
  end

  class ConnectionError < Error
    def initialize(faraday_error, params = {})
      super(params.merge(faraday: {
        message: faraday_error.message,
        response: faraday_error.response
      }))
    end
  end
end
```

But as `Airbrake.add_filter` is a global setting pretty sure that won't work.

----

Hope this helps illustrate why it would be useful to pass along data contained within custom error classes (such as ones defined by app developers or provided by libraries as with [Faraday::Error](https://github.com/lostisland/faraday/blob/master/lib/faraday/error.rb#L10)).

**Comment by kyrylo** [comment]
Thanks for the explanation. Could you please give this PR a try https://github.com/airbrake/airbrake-ruby/pull/113

Does it meet your requirements?
