### ISSUE TITLE
Context keys are not filtered

### ISSUE THREAD

**Issue by jani9000** [airbrake/airbrake-ruby#114]
Configuring with `c.blacklist_keys = [/password/i, 'email', 'name']` doesn't filter user's email and name. `Airbrake::Rack::NoticeBuilder` pulls the values from Warden and adds them to `context`.

I noticed `:context` is not part of `Airbrake::Filters::FILTERABLE_KEYS` https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/filters.rb#L8

I'm guessing I can work around the problem by writing a custom filter, but would be nice if the blacklist applied to `:context`.

**Comment by kyrylo** [comment]
Currently, the way it works is that you can filter the `user` key, but can't filter individual user attributes. Thus, this will work:

```rb
c.blacklist_keys = [:user]
```

Do you need to be able to filter individual user keys, or will the solution above work for you?

**Comment by jani9000** [comment]
I do need to filter individual keys. I need to send an opaque user ID because it helps me analyze problems, but filter out any personally identifiable information (PII) for compliance reasons. This is probably the case for pretty much any big company.

I got around this by rolling my own filter, so I'm good for now.

**Comment by kyrylo** [comment]
Thanks for the information. I agree that we do need to add better user filtering. However we don't want to allow filtering of some context payload to avoid modifications of private information, which we don't want to be changed.
