### ISSUE TITLE
Why Airbrake v5 doesn't allow reconfiguration

### ISSUE THREAD

**Issue by huynhquancam** [airbrake/airbrake-ruby#127]
I was wondering why Airbrake version 5 doesn't allow reconfiguration.

There are some certain cases I think reconfiguration is needed. For example I want to change the logger for Sidekiq or for other processes forked Rails.

**Comment by kyrylo** [comment]
Hey, @huynhquancam! It's not allowed because it turned out it's not really needed so far. Reconfiguration also makes debugging more complex. 

I'm not sure I understand your scenario. If you need a new logger, just configure a new notifier. Let me know what you think.
