### ISSUE TITLE
Unnecessary airbrake error when running unknown rake task

### ISSUE THREAD

**Issue by khustochka** [airbrake/airbrake-ruby#13]
* Airbrake version: 5.0.1
* Ruby version: 2.2.3
* Framework name & version: Rails 4.2.5

#### Airbrake config

````
  Airbrake.configure do |config|
    config.project_id = <project_id>
    config.project_key = <project_key>
    config.host = <host>
    config.ignore_environments = [:test]
  end
````

#### Description

I checked that my config is OK by running `rake airbrake:test`, it runs successfully.

But when I run a rake task that does not exist I am getting the following output:

````
$ bin/rake kokoko:dskfkl
rake aborted!
Don't know how to build task 'kokoko:dskfkl'

(See full trace by running task with --trace)
/Users/vkhustochka/.rvm/gems/ruby-2.2.3@quails/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby.rb:282:in `call_notifier': the 'default' notifier isn't configured (Airbrake::Error)
	from /Users/vkhustochka/.rvm/gems/ruby-2.2.3@quails/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby.rb:149:in `notify_sync'
	from /Users/vkhustochka/.rvm/gems/ruby-2.2.3@quails/gems/airbrake-ruby-1.0.1/lib/airbrake-ruby.rb:291:in `block in <top (required)>'
````

I think the issue is that in this case airbrake is loaded (through bundler) but initializers are not loaded, so Airbrake config is not loaded.

**Comment by khustochka** [comment]
The same also happens for any rake task (even if it was successful) if Airbrake is not configured.

**Comment by kyrylo** [comment]
Thanks for the bug report. Could you please verify that the fix presented in https://github.com/airbrake/airbrake-ruby/pull/14 works for you?

Merry Christmas! =)

**Comment by vmihailenco** [comment]
>The same also happens for any rake task (even if it was successful) if Airbrake is not configured.

Do you mean that Airbrake is always not configured?

**Comment by khustochka** [comment]
@vmihailenco I think I meant it fails for rake tasks that do not load rails environment.

**Comment by khustochka** [comment]
@kyrylo Yes, it fixes the problem. Thank you.

**Comment by rafaelgonzalez** [comment]
* Airbrake version: 1.0.2
* Ruby version: 2.2.3
* Framework name & version: Rails 4.2.5

#### Airbrake config

```
Airbrake.configure do |config|
  config.project_id = 'foo'
  config.project_key = 'bar'

  config.ignore_environments = %w(development test)
end
```

#### Description

Hello, I am having a very similar error to this. It happens when RSpec's rake task exists because of a failing spec.

I'm using the latest version (`1.0.2`) and I'm not quite sure why #14 does not apply in this case, as it seems to be `SystemExit` as well.

I removed some irrelevant output from RSpec, but the output I get is this:

```
$ RAILS_ENV=test rake spec

--Snip--

Finished in 4.02 seconds (files took 2.22 seconds to load)
97 examples, 1 failure

Failed examples:

--Snip--

Randomized with seed 50266

/Users/rafaelgonzalez/.rvm/rubies/ruby-2.2.3/bin/ruby -I/Users/rafaelgonzalez/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib:/Users/rafaelgonzalez/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.4.1/lib /Users/rafaelgonzalez/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
rake aborted!
Airbrake::Error: the 'default' notifier isn't configured
/Users/rafaelgonzalez/.rvm/gems/ruby-2.2.3/gems/airbrake-ruby-1.0.2/lib/airbrake-ruby.rb:282:in `call_notifier'
/Users/rafaelgonzalez/.rvm/gems/ruby-2.2.3/gems/airbrake-ruby-1.0.2/lib/airbrake-ruby.rb:236:in `build_notice'
/Users/rafaelgonzalez/.rvm/gems/ruby-2.2.3/gems/airbrake-5.0.2/lib/airbrake/rake/task_ext.rb:21:in `rescue in execute'
/Users/rafaelgonzalez/.rvm/gems/ruby-2.2.3/gems/airbrake-5.0.2/lib/airbrake/rake/task_ext.rb:19:in `execute'
SystemExit: exit
/Users/rafaelgonzalez/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/rake_task.rb:84:in `exit'
/Users/rafaelgonzalez/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/rake_task.rb:84:in `run_task'
/Users/rafaelgonzalez/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/rake_task.rb:96:in `block (2 levels) in define'
/Users/rafaelgonzalez/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/rake_task.rb:94:in `block in define'
/Users/rafaelgonzalez/.rvm/gems/ruby-2.2.3/gems/airbrake-5.0.2/lib/airbrake/rake/task_ext.rb:19:in `execute'
Tasks: TOP => spec
(See full trace by running task with --trace)
```

Let me know if you would prefer a separate issue for this, I'm posting here since the issue seems fairly similar.

**Comment by kyrylo** [comment]
@rafaelgonzalez what happens when you configure your Airbrake inside `spec_helper.rb` (simply copy-paste the config)?

**Comment by kyrylo** [comment]
Do you get the same results with:

* `rake spec` (without the env specifier)
* `bundle exec rake`

**Comment by davidrf** [comment]
@kyrylo @rafaelgonzalez I had the same problem of having that stack trace show up when the tests failed when invoking rake. Placing my Airbrake inside `spec_helper.rb` gave me `'configure': the 'default' notifier was already configured (Airbrake::Error)`. Also, running the tests with `rspec` did not raise the stack trace. I actually managed to get the stack trace to go away by placing the following at the bottom of my Rakefile (which isn't great either).
```ruby
Airbrake.configure do |config|
  config.project_key = ''
  config.project_id = ''
end
```

**Comment by kyrylo** [comment]
Please file an issue. This seems to be a different problem.

**Comment by rafaelgonzalez** [comment]
@kyrylo 

> @rafaelgonzalez what happens when you configure your Airbrake inside spec_helper.rb (simply copy-paste the config)?

If I add the airbrake config to my `spec_helper.rb` like so:

```ruby
require 'simplecov'
SimpleCov.start 'rails'

require 'factory_girl_rails'
require 'airbrake'

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.filter_run :focus
  config.run_all_when_everything_filtered = true

  config.disable_monkey_patching!

  if config.files_to_run.one?
    config.default_formatter = 'doc'
  end

  config.order = :random

  Kernel.srand config.seed

  config.include FactoryGirl::Syntax::Methods
end

Airbrake.configure do |config|
  config.project_id = 'foo'
  config.project_key = 'bar'

  config.environment = Rails.env # I added this the config since my previous post, but removing it does not affect this issue
  config.ignore_environments = %w(development test)
end
```

Sorry for the verbosity, just want to give you as much context as possible.

> Do you get the same results with:
>
> - `rake spec` (without the env specifier)
> - `bundle exec rake`

- `rake spec` does not output anything for me when not specifying the environment (I suspect this is because RSpec is under the `:test:` group in my Gemfile)

- `bundle exec rspec` does **not** trigger the error when specs fail.

- `bundle exec rake` does trigger the error when specs fail (this is how I came across this issue in the first place)
