### ISSUE TITLE
support return values in async mode

### ISSUE THREAD

**Issue by grosser** [airbrake/airbrake-ruby#138]
it would be great to get back a url even in async mode, could be done by for example generating a UUID on the client and sending that to the server ... then the client can ask for that UUID later and get the response if any ... this would allow bringing back the user-informer ... and allow linking airbrakes to errors seen in the logs

**Comment by kyrylo** [comment]
Could you show some [pseudo]code how you did it before, in v4? Do you simply want to get return values from `uuid = Airbrake.notify`?

**Comment by grosser** [comment]
previously I relied on the user informer working ... if I had to rebuild it manually then I'd want something like `uuid = Airbrake.notify` ... or `url = Airbrake.notify` so I don't have to use notify_sync

**Comment by kyrylo** [comment]
@grosser could you check this PR: https://github.com/airbrake/airbrake-ruby/issues/143

I think it'll allow you to get the user informer functionality back.

**Comment by grosser** [comment]
Looked more into building user informer, but it's still sad that it would have to block the request since it waits for the notice to be delivered ... how about generating the UUID for `/locate` on the client and then returning that from the notice call ... this way we don't block the request and our users can report an error id that will lead us directly to the problem. (for weird edge-cases like duplicate UUID the call would simply fail)

**Comment by kyrylo** [comment]
I'm sorry, I can't offer anything better than what we have right now. It's would be quite a change on our end. From the positive side, I suspect this used to work in v4 in a similar blocking fashion, so in v5 we at least can guarantee the same functionality.

**Comment by grosser** [comment]
Yeah I understand that it's not easy, maybe something put put on the
roadmap / plan for ... would be a more lightweight way of doing things.
Current state is ok since I'd guess few people use the notifier
functionality.

**Comment by kyrylo** [comment]
I just filed an internal issue about this. I'll keep you posted if we come up with something.

**Comment by grosser** [comment]
FYI just whipped up https://github.com/grosser/airbrake-user_informer which uses the promise api to bring back the user-informer ... not that much code inc case you want to bring that feature back :)

**Comment by kyrylo** [comment]
Thanks. I checked the code but I don't see how it's different from `Airbrake.notify_sync`. Here's how we implement it now: https://github.com/airbrake/airbrake-ruby/blob/2c1aced543181c565052e5e4c98c6f169f359861/lib/airbrake-ruby/notifier.rb#L57-L59

Essentially, it's `Airbrake.notify('foo').value`. `value` will block and return a response.

**Comment by grosser** [comment]
Yep, it's exactly the same :D
(idk how to make this async ... could add a new endpoint, but that's a bit messy)
... the 'feature' is that it brings back the user-information on error pages.

**Comment by grosser** [comment]
the new notify_sync implementation is neat!

**Comment by grosser** [comment]
... I could also use .value I guess ... but I'd want a timeout around it ... I'll check that out :)

**Comment by grosser** [comment]
`.value` does not block ... it returns a hash that might be the response (if notice finished finished) or get filled with error 

```
Benchmark.realtime { puts Airbrake.notify('foo').value }
{}
=> 0.0032933377660810947
```

**Comment by kyrylo** [comment]
Looks like you are right. I'm sorry that I confused both myself and you. I'd love `.value` to be blocking, though. Currently, it's no easy task because we use a thread pool for async delivery, so we cannot really call `join` to block and return that value.

**Comment by grosser** [comment]
using this atm to get it 'blocking' ... not saying it's great, but it seems to work :D

```Ruby
      # https://github.com/grosser/airbrake-user_informer/blob/master/lib/airbrake/user_informer.rb#L39-L50
      def wait_for_error(promise)
        return unless promise
        done = false
        error_id = nil
        promise.then { |notice| error_id = done = notice["id"] }
        promise.rescue { |_notice| done = true }
        STEPS.times do
          break if done
          sleep TIMEOUT / STEPS
        end
        error_id
      end
```
