### ISSUE TITLE
Using persistent queues for async notices

### ISSUE THREAD

**Issue by ramkumar-kr** [airbrake/airbrake-ruby#142]
* Airbrake version: Upgrading from 4.3.3 to 5.5.0
* Ruby version: 2.0
* Framework name & version: Rails 4.2 and Unicorn 4.9

Due to airbrake's new async notifier, the queue is now a part of the main application code and the queue is cleared(or destroyed) when the application itself crashes.

Is there a way to use persistent queues so that I don't lose any notifications?

**Comment by kyrylo** [comment]
That's not possible right now, but it's an interesting idea. I think the simplest solution would be using [PStore](http://ruby-doc.org/stdlib-2.3.3/libdoc/pstore/rdoc/PStore.html).

**Comment by kyrylo** [comment]
Implementation won't be trivial. I'll be happy to revisit this idea if more people express interest in this feature. That's for sharing this idea @ramkumar-kr.

**Comment by xgt001** [comment]
+1 for this. @kyrylo can I give this a shot if you don't mind ? :)

**Comment by kyrylo** [comment]
I don't mind, thank you 👍
