### ISSUE TITLE
Can't reach a host with a subpath

### ISSUE THREAD

**Issue by damuz91** [airbrake/airbrake-ruby#144]
Awesome tool!,
Trying to explore the concept of error catching with Airbrake client and with Errbit; Tried succesfuly in local environment with multiple applications and porting on localhost but when i try to deploy on a VPS with separate application with subpaths i can't get the Airbrake-ruby (or Airbrake 5 gem) to reach a subpath using the host attribute in the configuration.

https://github.com/airbrake/airbrake-ruby#host

`config.host = 'http://my-website.com/errbit'`

But if i move my errbit alias to `/` i get it working perfectly. 
Currently when i do `rake airbrake:test` it throws a 404 error. 

So far i've followed the code up to the endpoint method which calls the host attribute, but i am not sure why it won't work while using host + subpath as the entire host

https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/config.rb#L102

Any ideas on how to proceed?
Thank you!

Edit: Uh oh, should i've posted this on airbrake instead of airbrake-ruby

Edit 2: Aha!, Ok, see how interesting. At the end of that endpoint method the class makes a call to `URI.join`, and just figured the following behaviour:

`2.3.1 :003 > URI.join('http://localhost/monitoring/','/api/etc')`
` => #<URI::HTTP http://localhost/api/etc> `

Note that it trashes away the subpath of the first parameter of the .join method, like only accepting the protocol and the domain (and the port). A solution to my problem would be to keep using my errbit under a port :(, or [even better understand how the URI class works](http://apidock.com/ruby/URI/join/class), but as the endpoint method is implemented i see that i have no other option than rewriting this method.

i wonder how can i extend it?

**Comment by kyrylo** [comment]
Hi, this is the correct repository to file your issue against. This is a bug, so no need to fix anything on your end. Thanks for the investigations!

**Comment by damuz91** [comment]
Hehe, good not to piss anyone for this.
I'd like to know if i can make any workaround on this.. i was thinking on something like adding a separate initializer with a monkey patch that would look like this:

`module Airbrake
  class Config
    def endpoint
        @endpoint ||=
        begin
            self.host = ('https://' << host) if host !~ %r{\Ahttps?://}
            api = "/api/v3/projects/#{project_id}/notices?key=#{project_key}"
            self.host = self.host[0...-1] if self.host[-1] == '/'
            "#{host}#{api}"
        end
    end
  end
end`

Just an ugly quick thought, what do you think?

**Comment by kyrylo** [comment]
So you say this doesn't work:

```rb
config.host = 'http://my-website.com/errbit'
```

I think the easiest way to fix this problem would be appending a trailing slash:

```rb
config.host = 'http://my-website.com/errbit/'
```

Let me know if this works.

**Comment by damuz91** [comment]
None did work :(

**Comment by kyrylo** [comment]
This was fixed, so once we release the library, you will be able to configure it like this:

```rb
config.host = 'http://my-website.com/errbit/'
```

**Comment by rajdeep26** [comment]
Thanks @kyrylo for the [comment](https://github.com/airbrake/airbrake-ruby/issues/144#issuecomment-270630888)

I was stuck on this for some time because of the missing trailing slash. Won't it be better to mention this somewhere on the README file?

**Comment by kyrylo** [comment]
That is a good idea. Added in https://github.com/airbrake/airbrake-ruby/pull/361.

**Comment by rajdeep26** [comment]
Great! Thanks a lot 👍
