### ISSUE TITLE
Global context via config ?

### ISSUE THREAD

**Issue by grosser** [airbrake/airbrake-ruby#164]
I want to send a few pieces of context on every request, something like:

```
Airbrake.configure do |config|
  config.context = ['HOST_IP', 'POD_NAME', 'POD_NAMESPACE', 'REVISION', 'TAG'].
    map { |k| [k.downcase, ENV[k]] }.to_h
end

Airbrake.notify("kaboom") # correct context
```

I can trivially get this by writing a wrapper method, but might be a nice feature to simplify setup

**Comment by kyrylo** [comment]
I'm sorry, could you elaborate? I read this multiple times but I'm afraid I don't understand what you want.

**Comment by zefer** [comment]
Hi Michael. Unless I misunderstood, this will do what you ask:

```rb
extra_context = %w(HOST_IP POD_NAME POD_NAMESPACE REVISION TAG).map do |k|
  [k.downcase, ENV[k]]
end.to_h

Airbrake.add_filter do |notice|
  notice[:context] = notice[:context].merge(extra_context)
end
```

**Comment by grosser** [comment]
awesome! :D
