### ISSUE TITLE
Docs out of date for sending current_user information?

### ISSUE THREAD

**Issue by ratbeard** [airbrake/airbrake-ruby#166]
I was trying to get user information associated with an error working, [mentioned in the readme](https://github.com/airbrake/airbrake#additional-features-user-reporting-sophisticated-api)

Looks like some options related to it were removed in the [migration to 5](https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md).  My guess is that also changed it so the Airbrake::Rack::User middleware is no longer automatically inserted?  I see it still exists, but it doesn't look to be used:

https://github.com/airbrake/airbrake/blob/a77b20bbdb1cd089b775d613482552f067b0c4df/lib/airbrake/rack/user.rb

https://github.com/airbrake/airbrake/blob/05e66f4941d4cedcb690124703b63ec0b498c293/lib/airbrake/rails/railtie.rb

If so, what's the recommended way to insert this middleware?

**Comment by kyrylo** [comment]
If you use `Airbrake::Rack::Middleware` (and I assume you use Rails), then we extract user info [here](https://github.com/airbrake/airbrake/blob/2a6f47a5c1a129df584ab6c4cded331c54899f0f/lib/airbrake/rack/context_filter.rb#L37).

Basically, anything that uses `Airbrake::Rack::Middleware` also supports our user extraction mechanism.

**Comment by ratbeard** [comment]
Oh ok, I'll do some investigation on our side why its not getting set.  Just realized github's code search results page only shows the first few matches in a file so I didn't see that line  🤕 

Thank you!

**Comment by kyrylo** [comment]
Happy Airbraking! FYI we support Devise and OmniAuth and have tests for those cases. There's a chance that you use something other than these, hence we can't guess the user.

**Comment by ratbeard** [comment]
Yea, we have a custom auth solution.  I thought it would work since we call the method `current_user`, but looks like the problem is we don't set that on rack.env.  Might want to add our own custom middleware modeled off yours so we can send other data we're interested in for the user, like their organization name.

Cheers! 🍾
