### ISSUE TITLE
use a default for root_directory

### ISSUE THREAD

**Issue by grosser** [airbrake/airbrake-ruby#167]
something sensible would be nice to avoid having to always set it ...

`(defined?(Bundler) && Bundler.root.to_s) || File.expand_path(Dir.pwd)`

**Comment by kyrylo** [comment]
I don't see why not. Would you mind sending a PR?

P.S. `Bundler.root.to_s` can be `Bundler.root` because we accept `Pathname`'s.

**Comment by grosser** [comment]
done: https://github.com/airbrake/airbrake-ruby/pull/171
