### ISSUE TITLE
Add docs for usage of Notifier.create_deploy()

### ISSUE THREAD

**Issue by zachgoldstein** [airbrake/airbrake-ruby#175]
I see `Notifier.create_deploy()` exists, but there are no docs about it's use in this repo.
https://github.com/airbrake/airbrake-ruby/blob/8c8344eaee613835e22ec2570744e05fb87066fd/lib/airbrake-ruby/notifier.rb#L90

Would be awesome to add a quick note of this.

**Comment by kyrylo** [comment]
I'm so far not sure we need to highlight that method. It only exists for `airbrake/airbrake` consumption, so if I had the choice not to expose it, I wouldn't. Why do you think our users would want to use it?

**Comment by zachgoldstein** [comment]
If somebody wanted to create some sort of integration that used deploy tracking, where would they look right now? They would have to dig and look at how the rake task works and then build off that (https://github.com/airbrake/airbrake/blob/05e66f4941d4cedcb690124703b63ec0b498c293/lib/airbrake/rake/tasks.rb#L77). If the rake task uses the method here, shouldn't it be documented here?

Anyways, doesn't look like anybody actual does this, but I do think it would be good to add for completeness.

**Comment by kyrylo** [comment]
Fixed by https://github.com/airbrake/airbrake-ruby/pull/177.
