### ISSUE TITLE
override exception message ?

### ISSUE THREAD

**Issue by grosser** [airbrake/airbrake-ruby#179]
this used to work ... but now it only gives saves the error message ... would be nice to either make it work again or have a deprecation

`Airbrake.notify($!, error_message: "Foobar")`

**Comment by kyrylo** [comment]
In my humble opinion, it's too late for deprecations. It was silently removed in the very first version of airbrake v5 (basically, when this gem was introduced).

I am not quite sure why you want to do this. In theory, you can use `add_filter` to override it, but without any context it's hard for me to suggest anything better.

**Comment by grosser** [comment]
yeah I guess so ... just updated an old project and ran into this :)
we used to add a custom message for more details ... but `e.message << ' -- foobar'` also works ...

**Comment by grosser** [comment]
that did not work out ... ran into a few `cannot modify frozen string` errors :(
... can we add a way to override or append the exception message ?

**Comment by grosser** [comment]
for now using:

```
reason = "compare failed"
warn "#{reason}\n#{$!.message}"
Airbrake.notify($!, reason: reason)
```

**Comment by kyrylo** [comment]
I'm not sure I like this feature. I think once we implement https://github.com/airbrake/airbrake-ruby/issues/187 this won't be needed.
