### ISSUE TITLE
Save context of a current thread

### ISSUE THREAD

**Issue by dmitry** [airbrake/airbrake-ruby#187]
Lets assume we have a complex logic, which has multiple steps, and you can't access previous variables that affects on the current state of logic where an exception happened. Right now it's not possible to find out how it came into current state, except to go through the logger for the same time. Would be nice to save context in a `Thread.current` and use it inside the `Notifier`.

**Comment by kyrylo** [comment]
Is this similar to what you would like to have?
https://github.com/airbrake/airbrake/issues/696

**Comment by dmitry** [comment]
@kyrylo right, the one honeybadger also has.

**Comment by kyrylo** [comment]
Thanks, this makes sense and we definitely want to support this feature.

**Comment by kyrylo** [comment]
I made a PR that adds support for this feature:
https://github.com/airbrake/airbrake-ruby/issues/194

@dmitry @phstc could you guys give it a spin and let me know if it works for you?

**Comment by dmitry** [comment]
@kyrylo I can check only in 1 week after I get back from the vacations.
