### ISSUE TITLE
Airbrake notification doesn't start from a thread running on a rake task

### ISSUE THREAD

**Issue by FabioRos** [airbrake/airbrake-ruby#193]
`Airbrake.notify_sync` is working fine. However, if I use `Airbrake.notify`, errors won't be intercepted by Airbrake. Any Ideas?
Thank you in advance

**Comment by kyrylo** [comment]
Does your program exit before `Airbrake.notify` finishes its job?

**Comment by FabioRos** [comment]
That's the problem. My Bad. Sorry

**Comment by kyrylo** [comment]
No worries, feel free to post more issues when you find them 👍

**Comment by FabioRos** [comment]
Thank you! :)
