### ISSUE TITLE
Add Airbrake.configured? method

### ISSUE THREAD

**Issue by mvastola** [airbrake/airbrake-ruby#22]
Apologies if this actually exists somewhere and I'm totally blind, but I'm in the process of writing a PR for a new integration for `airbrake` (https://github.com/airbrake/airbrake/pull/472) and it occurs to me that it would be exceedingly helpful if there were a class method on the `Airbrake` module called `configured?` that returned a boolean to indicate if a `Notifier` had been configured (and thus existed).

This would be useful to test for because if the `airbrake` gem handles an exception that occurs before the `airbrake-ruby` configuration loads, a second exception will be triggered, making it 
  - more difficult to troubleshoot the first, and;
  - unnecessary/unhelpful/inadvisable for the `airbrake` gem to have intercepted anything in the first place

While the `airbrake` gem also makes use of the `Airbrake` module, it seems like `airbrake-ruby` would still be the proper location for the class method I am proposing.

I am happy to write the PR if needed, but seeing as that part is trivial (the actual function obviously will comprise just one line of code) I thought any necessary discussion should happen first..

**Comment by kyrylo** [comment]
Such a method existed in the previous version of the gem (`Airbrake.configuration.configured?`). While designing this library we were trying to make it as simple as possible. This method felt superfluous, so it was removed. I guess if you feel the need for it, then you should configure Airbrake earlier.

That said, I think I understand what you are talking about. I do agree that the message about "the default notifier" is annoying, but at the moment I am not convinced that your suggestion is the right way.  So far it was possible to write everything without it :)

**Comment by mvastola** [comment]
Hmm. Then mave my suggestion isn't quite the best solution, but one thing I'm just thinking in terms of is if, for instance, I have an app for which I want to configure `airbrake` as early as possible, but some ignore conditions should only be append later on in the load process because they interface with modules/gems that may not be loaded yet (or, worse, they might trigger the loading of a new dependency in the middle of a notification job). So I guess one thing that might be useful would be the ability to append configurations.

But I'm actually going to close this for now and wait utility my PR is more fully formed.. I think I got ahead of myself  (I also thought it was working better than it apparently is..)
