### ISSUE TITLE
Option to configure FilterChain::DEFAULT_FILTERS

### ISSUE THREAD

**Issue by dadah89** [airbrake/airbrake-ruby#246]
https://github.com/airbrake/airbrake-ruby/blob/v2.3.2/lib/airbrake-ruby/filter_chain.rb#L24

Calling `Airbrake.configure` calls Notice.new, which calls FilterChain.new, which always add FilterChain::DEFAULT_FILTERS. Unless I'm missing something, there doesn't seem to be a way to configure default filters, if for example I don't want Filters::ThreadFilter added.

Would be nice to have some sort of option or at least a `remove_filter` method (currently I'm monkey patching FilterChain to change the default list).

**Comment by kyrylo** [comment]
Hi @dadah89. I'm curious, why do you want to remove `ThreadFilter`?

**Comment by dadah89** [comment]
@kyrylo years of use and I never payed attention to that info (don't know of anyone around here who does), so I rather remove then and keep the notice clean. Also wanna avoid that by some mistake we send sensitive information to your servers. So in my case, rather than filtering, just skipping it would be ideal.

**Comment by kyrylo** [comment]
I don't mind making it optional, but I would love to see more opinions (in case anyone stumbled upon this issue). Right now it doesn't seem to hurt anyone, so my gut feeling tells me it's okay to leave it as is. I will leave this issue open for some time, but it'll be closed if nobody else speaks up.

P.S. If you send a notice by mistake, you can always delete the whole group via our API: https://airbrake.io/docs/api/#delete-group-v4
If I find that this is a common thing, we can always make it opt-in.

**Comment by kyrylo** [comment]
Leaving as is. To whom it may concern: please speak up if you want it to be optional.
