### ISSUE TITLE
blacklist of HTTP_COOKIE does not work

### ISSUE THREAD

**Issue by wlipa** [airbrake/airbrake-ruby#256]
A blacklist like:

    config.blacklist_keys = [ /password/i, '_csrf_token', 'HTTP_COOKIE' ]

does not filter the HTTP_COOKIE field within the context "headers" hash.  It still appears in the airbrake data, like:

    Context:
    {
      "headers":  {
        "HTTP_COOKIE": "__utma=132227739.1350222162.1472268603.1506...

I'd like to have an easy way to remove named fields, no matter where they appear in the airbrake data.

**Comment by wlipa** [comment]
Did this make it in 2.4.1?  I can't see the commits in master.

**Comment by wlipa** [comment]
Thanks!

**Comment by kyrylo** [comment]
v2.4.2 is out. Enjoy!
