### ISSUE TITLE
Airbrake-ruby doesn't report error if newrelic_rpm is installed

### ISSUE THREAD

**Issue by mtsmfm** [airbrake/airbrake-ruby#27]
* Airbrake version: 5.0.2
* Airbrake-ruby version: 1.0.2
* Ruby version: 2.3.0
* Framework name & version: Rails 4.2.5

#### Airbrake config

config/initializers/airbrake.rb

```ruby
# Airbrake is an online tool that provides robust exception tracking in your Rails
# applications. In doing so, it allows you to easily review errors, tie an error
# to an individual piece of code, and trace the cause back to recent
# changes. Airbrake enables for easy categorization, searching, and prioritization
# of exceptions so that when errors occur, your team can quickly determine the
# root cause.
#
# Configuration details:
# https://github.com/airbrake/airbrake-ruby#configuration
Airbrake.configure do |c|
  # You must set both project_id & project_key. To find your project_id and
  # project_key navigate to your project's General Settings and copy the values
  # from the right sidebar.
  # https://github.com/airbrake/airbrake-ruby#project_id--project_key
  c.project_id = ENV['AIRBRAKE_PROJECT_ID']
  c.project_key = ENV['AIRBRAKE_API_KEY']

  # Configures the root directory of your project. Expects a String or a
  # Pathname, which represents the path to your project. Providing this option
  # helps us to filter out repetitive data from backtrace frames and link to
  # GitHub files from our dashboard.
  # https://github.com/airbrake/airbrake-ruby#root_directory
  c.root_directory = Rails.root

  # By default, Airbrake Ruby outputs to STDOUT. In Rails apps it makes sense to
  # use the Rails' logger.
  # https://github.com/airbrake/airbrake-ruby#logger
  c.logger = Rails.logger

  # Configures the environment the application is running in. Helps the Airbrake
  # dashboard to distinguish between exceptions occurring in different
  # environments. By default, it's not set.
  # https://github.com/airbrake/airbrake-ruby#environment
  c.environment = Rails.env

  # Setting this option allows Airbrake to filter exceptions occurring in
  # unwanted environments such as :test. By default, it is equal to an empty
  # Array, which means Airbrake Ruby sends exceptions occurring in all
  # environments.
  # https://github.com/airbrake/airbrake-ruby#ignore_environments
  c.ignore_environments = %w(test)
end if defined?(Airbrake)

# If Airbrake doesn't send any expected exceptions, we suggest to uncomment the
# line below. It might simplify debugging of background Airbrake workers, which
# can silently die.
# Thread.abort_on_exception = ['test', 'development'].include?(Rails.env)
```

#### Description

Following command raise exception, but Airbrake doesn't report about it:

    $ heroku run rails r 'raise'

It happens if we installed newrelic_rpm.

I think `$ERROR_INFO` changed to nil in newrelic's at_exit hook.

- https://github.com/newrelic/rpm/blob/3.14.1.311/lib/new_relic/agent/agent.rb#L389-L397
- https://github.com/airbrake/airbrake-ruby/blob/v1.0.2/lib/airbrake-ruby.rb#L292

If we rescued some exceptions on at_exit hook, `$ERROR_INFO` (`$!`) is changed to nil.

```ruby
$ ruby -e 'at_exit { p $! }; raise'  
# RuntimeError
```

```ruby
$ ruby -e 'at_exit { p $! }; at_exit { raise rescue nil }; raise'        
# nil
```

So I think we shouldn't use at_exit hook to report unhandled errors.

##### Workaround

We can disable newrelic's at_exit hook on our newrelic.yml:

```yaml
production:
  <<: *default_settings
  send_data_on_exit: false
```

**Comment by kyrylo** [comment]
Hello, @mtsmfm! Thanks for a high class report :)
I believe we can't do much here.

> So I think we shouldn't use at_exit hook to report unhandled errors.

 `at_exit` is still useful to us because it can catch fatal exceptions. `$!` is a special variable that we rely on. There's no other way to handle fatal exceptions better. I suggest you to file an issue at newrelic_rpm's bug tracker to see their answer. Maybe there's a way for them to re-raise the exception (or set it manually).

Thanks for the workaround advice. I can also suggest another workaround. 

Given:

```ruby
$ ruby -e 'at_exit { p $! }; at_exit { raise rescue nil }; raise'
# nil
```

Try this instead:

```ruby
$ ruby -e 'at_exit { raise rescue nil }; at_exit { p $! }; raise'
RuntimeError
```

As you can see the order of defined `at_exit` hooks matters.

```ruby
% ruby -e 'at_exit { puts 1 }; at_exit { puts 2 }; at_exit { puts 3 }'
3
2
1
```

Try to load the Airbrake gem *after* newrelic_rpm.

**Comment by kyrylo** [comment]
There's another workaround that can work:

```ruby
ruby -e 'trap("EXIT") { p $! }; at_exit { raise rescue nil }; raise'
# RuntimeError
```

**Comment by kyrylo** [comment]
I don't recommend to use trap, though. It doesn't support multiple callbacks. [I have implemented](https://github.com/kyrylo/multitrap) a hacky gem that adds support for it, but it's untested in production.
