### ISSUE TITLE
"Cannot unmarshal string into Go struct field StackFrame.line" after truncating big notices

### ISSUE THREAD

**Issue by m5rk** [airbrake/airbrake-ruby#285]
We're unable to send airbrakes with Rails 5.1 and airbrake 7.1.0, airbrake-ruby 2.6.0. We get this error in our heroku logs:

```
**Airbrake: json: cannot unmarshal string into Go value of type models.StackFrame 
```

**Comment by m5rk** [comment]
[airbrake-pp.json.txt](https://github.com/airbrake/airbrake-ruby/files/1510788/airbrake-pp.json.txt)

**Comment by m5rk** [comment]
I posted the notice json, but deleted it because it has some slightly sensitive information in it.

**Comment by m5rk** [comment]
Here's a relevant snippet:

```json
        {
          "file": "[GEM_ROOT]/gems/rack-timeout-0.4.2/lib/rack/timeout/support/timeout.rb",
          "line": "[Circular]",
          "function": "timeout",
          "code": {
            "17": "    thr = Thread.current                                    # reference to current thread to be used in timeout thread",
            "18": "    job = @scheduler.run_in(secs) { @on_timeout.call thr }  # schedule this thread to be timed out; should get cancelled if block completes on time",
            "19": "    return block.call                                       # do what you gotta do",
            "20": "  ensure                                                    #",
            "21": "    job.cancel! if job                                      # cancel the scheduled timeout job; if the block completed on time, this"
          }
        },

```

**Comment by saks** [comment]
same problem here, we keep getting errors like:
```
**Airbrake: json: cannot unmarshal string into Go struct field StackFrame.line of type int
```
when trying to notify a message using `Airbrake.notify` or `notify_airbrake`

**Comment by m5rk** [comment]
The workaround we used:

```ruby
# TODO: Remove these constraints (and the line for airbrake-ruby) once truncation bug in Airbrake is fixed.
gem 'airbrake-ruby', '2.5.1'
gem 'airbrake', '7.0.3'
```

**Comment by saks** [comment]
We do it similar way:
```
gem 'airbrake-ruby', '2.5.1'
gem 'airbrake'
```
It looks like the latest version of "airbrake" gem is fine

**Comment by kyrylo** [comment]
Hey guys, sorry about this bug.

Can anybody try out this PR? https://github.com/airbrake/airbrake-ruby/pull/286
I think it'll fix the issue but prior to merging, I'd like to get a confirmation.

**Comment by kyrylo** [comment]
I'm going to merge it today and release a new version nevertheless because this bug is critical.

**Comment by kyrylo** [comment]
Released this fix in v2.6.1.

**Comment by saks** [comment]
I've upgraded to the latest version (sorry had no chance to get to it earlier) and seems still having this problem:
Gemfile.lock:
```
    airbrake (7.1.0)
      airbrake-ruby (~> 2.5)
    airbrake-ruby (2.6.1)
```
Log:
```
E, [2017-12-01T18:26:26.697504 #8] ERROR -- : **Airbrake: json: cannot unmarshal string into Go struct field StackFrame.code of type map[int]string
```

**Comment by kyrylo** [comment]
Please upgrade to v2.6.2. I *hope* this bug is fixed.

**Comment by JasonBarnabe** [comment]
This version is seems to be working for me.

**Comment by kyrylo** [comment]
Thanks for testing, that's good news!
