### ISSUE TITLE
Support for regex in 'ignore_environments'

### ISSUE THREAD

**Issue by vraravam** [airbrake/airbrake-ruby#298]
In a rails codebase that I inherited, we have multiple test environments for automated qa, and other envs that end in the word 'test'. I would like to be able to manage/configure airbrake so that the 'ignore_environments' setting accepts a regex pattern as elements of the array (similar to 'blacklist_keys').

**Comment by kyrylo** [comment]
Sounds like a valid request, and it shouldn't be too hard to implement.

**Comment by vraravam** [comment]
tx for the quick turnaround @kyrylo

**Comment by kyrylo** [comment]
You're welcome. Already released, update to v2.8.0 :)
