### ISSUE TITLE
TypeError: can't move to the enclosed thread group

### ISSUE THREAD

**Issue by meetme2meat** [airbrake/airbrake-ruby#312]
Calling `Airbrake.notify` on Thread applications can result in a Thread been assign to an already enclosed ThreadGroup

The issue is very hard to replicate(but still we have 5-6 report of the above error in past 2 months) since it depends on the OS ability to context switch at wrong place resulting in a deadlock/race conditions on a shared object. 

The relevant code that been referred over here is `spawn_workers` inside the [async_sender.rb](https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/async_sender.rb#L95-L99)

Following is the backtrace reported by Airbrake.

```
TypeError: can't move to the enclosed thread group

org/jruby/RubyThreadGroup.java:87 in add
/gems/airbrake-ruby-1.1.0/lib/airbrake-ruby/async_sender.rb:93 in block in spawn_workers
org/jruby/RubyFixnum.java:296 in times
/gems/airbrake-ruby-1.1.0/lib/airbrake-ruby/async_sender.rb:93 in spawn_workers
/gems/airbrake-ruby-1.1.0/lib/airbrake-ruby/async_sender.rb:83 in has_workers?
/gems/airbrake-ruby-1.1.0/lib/airbrake-ruby/notifier.rb:130 in default_sender
/gems/airbrake-ruby-1.1.0/lib/airbrake-ruby/notifier.rb:45 in send_notice
/gems/airbrake-ruby-1.1.0/lib/airbrake-ruby/notifier.rb:45 in notify
/gems/airbrake-ruby-1.1.0/lib/airbrake-ruby.rb:282 in call_notifier
/gems/airbrake-ruby-1.1.0/lib/airbrake-ruby.rb:136 in notify
/srv/apps/policy_router/releases/20180212084654/lib/policy_router/response_handler.rb:52 in start
/srv/apps/policy_router/releases/20180212084654/lib/policy_router/request_handler.rb:7 in start
org/jruby/RubyKernel.java:1823 in public_send
/gems/celluloid-0.17.1.1/lib/celluloid/calls.rb:28 in dispatch
/gems/celluloid-0.17.1.1/lib/celluloid/call/sync.rb:16 in dispatch
/gems/celluloid-0.17.1.1/lib/celluloid/cell.rb:50 in block in dispatch
/gems/celluloid-0.17.1.1/lib/celluloid/cell.rb:76 in block in task
/gems/celluloid-0.17.1.1/lib/celluloid/actor.rb:338 in block in task
/gems/celluloid-0.17.1.1/lib/celluloid/task.rb:44 in block in initialize
/gems/celluloid-0.17.1.1/lib/celluloid/task/fibered.rb:14 in block in create
```

If need be I can share a sample script which I wrote to confirm the above issue.

Environment: 
* Airbrake version: 1.1.0
* Ruby version: JRuby-9.0.5.0 (openJDK 1.8)

**Comment by kyrylo** [comment]
Hi, thanks for reporting. I’d be curious to see the example script you mentioned.

**Comment by kyrylo** [comment]
I also strongly advise you to upgrade airbrake-ruby. The version you use is 2 years old and the latest version has a ton of new features and bug fixes.

**Comment by meetme2meat** [comment]
@kyrylo I have tested the Airbrake 2.8.3(with JRuby: **jruby-9.1.15.0**) version as well..

Here is the following result ... 

```
2.8.3
TypeError: can't move to the enclosed thread group
                     add at org/jruby/RubyThreadGroup.java:87
  block in spawn_workers at /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/airbrake-ruby-2.8.3/lib/airbrake-ruby/async_sender.rb:99
                   times at org/jruby/RubyFixnum.java:299
           spawn_workers at /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/airbrake-ruby-2.8.3/lib/airbrake-ruby/async_sender.rb:99
            has_workers? at /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/airbrake-ruby-2.8.3/lib/airbrake-ruby/async_sender.rb:88
          default_sender at /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/airbrake-ruby-2.8.3/lib/airbrake-ruby/notifier.rb:133
                  notify at /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/airbrake-ruby-2.8.3/lib/airbrake-ruby/notifier.rb:48
                  notify at /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/airbrake-ruby-2.8.3/lib/airbrake-ruby.rb:170
    block in deadlock.rb at deadlock.rb:14
```

Here is the following [script](https://gist.github.com/meetme2meat/ab9da6c9e57f25b7ad3605b7e86b785e)

Like I said the issue is very hard to replicate because of the OS ability to context switch threads at a wrong place. Hence to achieve that .. I have to apply `sleep` to replicate the same. The diff of the async_sender.rb is located [here](https://gist.github.com/meetme2meat/2142efb8ce9bfaaccdc9e8bc25ccfb16)

**Comment by kyrylo** [comment]
```
require 'airbrake-ruby'
puts Airbrake::AIRBRAKE_RUBY_VERSION
Airbrake.configure do |c|
  c.root_directory = Dir.pwd
  c.project_id     = 113743
  c.project_key    = '81bbff95d52f8856c770bb39e827f3f6'
  c.environment    = 'production'
end

Thread.abort_on_exception = true

$deadlock = true
Thread.new  {
  Thread.current[:id] = "1"
  Airbrake.notify("1+1")
}
sleep 1
Thread.new  {
 Thread.current[:id] = "2"
 Airbrake.notify("2+1")
}
sleep 20
```

Here's your script. I have a few questions. What is `$deadlock = true` for and what's the purpose of `Thread.current[:id] = "1"`?

**Comment by meetme2meat** [comment]
@kyrylo Sorry for the late reply

> Like I said the issue is very hard to replicate because of the OS ability to **context switch threads** at a wrong place. Hence to achieve that .. I have to apply sleep to replicate the same. The diff of the async_sender.rb is located [here](https://gist.github.com/meetme2meat/2142efb8ce9bfaaccdc9e8bc25ccfb16)

Maybe this ^^ explains  

On my development box,  I had to change to airbrake-ruby **async_sender.rb** file (the following) [code](https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/async_sender.rb#L82-L98) with the following diff [here](https://gist.github.com/meetme2meat/2142efb8ce9bfaaccdc9e8bc25ccfb16). All for to replicate the behaviour of (context switching of) OS pausing at a wrong place(When 2 or more thread are working on the same **shared variable**)

Let me know if you need anything else?

**Comment by meetme2meat** [comment]
@kyrylo Maybe you should redact the airbrake key that you posted above.

**Comment by kyrylo** [comment]
Apologies for the delay. I have been very busy with some other urgent work.
I managed to reproduce this error with the following simplified script:

```rb
require 'airbrake-ruby'

Airbrake.configure do |c|
  c.project_id = <id>
  c.project_key = <key>
end

t1 = Thread.new { Airbrake.notify(1) }
t2 = Thread.new { Airbrake.notify(2) }
t1.join
t2.join
```

I believe all it takes to fix the error is to wrap the body of the `AsyncSender#has_worker?` method into a mutex. I tested it locally and it seems to fix the error.

I submitted https://github.com/airbrake/airbrake-ruby/pull/316. Could you, please, test it?

**Comment by meetme2meat** [comment]
@kyrylo Sorry, Just back today from vacation. I have a question, are you publish the gem/release for this fix?. How am I suppose to get this changes? by setting the `git` (against) the master on Gemfile?

**Comment by kyrylo** [comment]
I haven't released it yet and I'll probably cut a new release this week.
In the meantime, yeah, you can point your Gemfile dependency to the master branch of this repo.

Thanks!

**Comment by meetme2meat** [comment]
@kyrylo Thanks.
