### ISSUE TITLE
Handshake Failure.

### ISSUE THREAD

**Issue by meetme2meat** [airbrake/airbrake-ruby#336]
We are seeing a lot of handshake failure issue. Although I see the issue are mostly due to NET/HTTP handshake failure. But can anything be done here?. Since for a given project we not seeing any new error notification getting logged in the Airbrake even though our log manager reports them.

> jruby-9.1.15.0 :002 > Airbrake.notify("TEST ERROR from Policy router")
>  => #<Airbrake::Promise:0xee395c @mutex=#<Mutex:0x79da2f0d>, @value={}, @on_resolved=[], @on_rejected=[]>
> jruby-9.1.15.0 :003 > E, [2018-07-06T10:21:49.582654 #13005] ERROR -- : **Airbrake: HTTP error: Received fatal alert: handshake_failure

**Comment by kyrylo** [comment]
[We've deprecated TLS 1.0 and 1.1](https://airbrake.io/blog/airbrake-news/tls-1-0-and-1-1-deprecation). I suspect this failure is related to the deprecation. I'd recommend [checking what TLS version your app uses](https://gist.github.com/bhelx/b0d5a03478e500644bbc) and upgrade your infrastructure accordingly.

**Comment by meetme2meat** [comment]
@kyrylo We are using TLS 1.2. So I doubt the deprecated versioning of TLS, would affect in this case. Any other clue?

**Comment by kyrylo** [comment]
I'm afraid right now I don't have a good answer but I'll get back to you once I come up with something.

**Comment by phumpal** [comment]
@meetme2meat can you please provide your jruby, java, and openssl versions?

**Comment by meetme2meat** [comment]
For now, using JRuby OpenSSL 0.9.21 seem to fix the issue. But I wonder why all a sudden it stopped working. 

Anyway closing the issue for now :).

**Comment by kyrylo** [comment]
Glad that you resolved it. Don't hesitate to reopen is it reoccurs again.
I still think it's related to the deprecation (timings match and your failure is related to SSL), we probably just don't have enough information to tie it to the error you saw.
