### ISSUE TITLE
One-off severity change

### ISSUE THREAD

**Issue by hakunin** [airbrake/airbrake-ruby#337]
This is what other error loggers let me do

```
<Logger>.error(...)
<Logger>.warning(...)
<Logger>.info(...)
```

Even chrome's console has this style of severity setting (`console.log`, `console.error`...)

And airbrake has this:

https://github.com/airbrake/airbrake-ruby#setting-severity

```
Airbrake.notify do |notice|
  notice[:context][:severity] = 'critical'
end
```

How do I achieve a one-off severity change for a specific debug into I want to send out?

**Comment by kyrylo** [comment]
Your link is correct, that is supposed to change severity. Is not working as expected?

**Comment by hakunin** [comment]
So how do I use it for a one off severity change?

Something like this?
```
Airbrake.notify(ex, {..more info..}) do |notice|
  notice[:context][:severity] = 'critical'
end
```

Or can I even do something like this?

```
Airbrake.notify(ex, {severity: 'critica'})
```

**Comment by kyrylo** [comment]
> Something like this?

That would be correct, yes.

> Or can I even do something like this?

No, that call does not change severity but sets `notice[:params][:severity]`.

**Comment by hakunin** [comment]
Thanks, is there any shorthand or do I have to use the block?

**Comment by kyrylo** [comment]
There's no shorthands. That is already a shorthand over this:

```ruby
notice = Airbrake.build_notice(ex)
notice[:context][:severity]
Airbrake.notify(notice)
```
