### ISSUE TITLE
Aibrake vs request_id

### ISSUE THREAD

**Issue by huguesbr** [airbrake/airbrake-ruby#338]
Is it possible to add the ActionDispatch uniq request id to the notice automatically or via any filter?
We haven't find a way to do so ourselves?

https://api.rubyonrails.org/classes/ActionDispatch/RequestId.html

**Comment by kyrylo** [comment]
Sure, it's trivial. Check out this default filter, which retrieves request body: https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rack/request_body_filter.rb

In your case the `call` method would be the following:

```ruby
def call(notice)
  return unless (request = notice.stash[:rack_request])
  notice[:params][:uuid] = request.uuid
end
```

P.S. you can ignore the `@weight` attribute completely until it gets in your way. It's needed to prioritise execution order of filters.

**Comment by huguesbr** [comment]
Oh, awesome. thank you!
