### ISSUE TITLE
"Malformed version number string" error with version 3.2.0

### ISSUE THREAD

**Issue by denisahearn** [airbrake/airbrake-ruby#407]
After upgrading from version 3.1.0 to version 3.20, I am now seeing the following error when my Rails application starts up:

/Users/denisahearn/.rvm/rubies/ruby-2.4.4/lib/ruby/site_ruby/2.4.0/rubygems/version.rb:209:in `initialize': Malformed version number string Git-113) (ArgumentError)
	from /Users/denisahearn/.rvm/rubies/ruby-2.4.4/lib/ruby/site_ruby/2.4.0/rubygems/version.rb:200:in `new'
	from /Users/denisahearn/.rvm/rubies/ruby-2.4.4/lib/ruby/site_ruby/2.4.0/rubygems/version.rb:200:in `new'
	from /Users/denisahearn/.rvm/gems/ruby-2.4.4@cloudvault/gems/airbrake-ruby-3.2.0/lib/airbrake-ruby/filters/git_repository_filter.rb:14:in `initialize'
	from /Users/denisahearn/.rvm/gems/ruby-2.4.4@cloudvault/gems/airbrake-ruby-3.2.0/lib/airbrake-ruby/notice_notifier.rb:208:in `new'
	from /Users/denisahearn/.rvm/gems/ruby-2.4.4@cloudvault/gems/airbrake-ruby-3.2.0/lib/airbrake-ruby/notice_notifier.rb:208:in `block in add_default_filters'
	from /Users/denisahearn/.rvm/gems/ruby-2.4.4@cloudvault/gems/airbrake-ruby-3.2.0/lib/airbrake-ruby/notice_notifier.rb:207:in `each'
	from /Users/denisahearn/.rvm/gems/ruby-2.4.4@cloudvault/gems/airbrake-ruby-3.2.0/lib/airbrake-ruby/notice_notifier.rb:207:in `add_default_filters'
	from /Users/denisahearn/.rvm/gems/ruby-2.4.4@cloudvault/gems/airbrake-ruby-3.2.0/lib/airbrake-ruby/notice_notifier.rb:56:in `initialize'
	from /Users/denisahearn/.rvm/gems/ruby-2.4.4@cloudvault/gems/airbrake-ruby-3.2.0/lib/airbrake-ruby.rb:242:in `new'
	from /Users/denisahearn/.rvm/gems/ruby-2.4.4@cloudvault/gems/airbrake-ruby-3.2.0/lib/airbrake-ruby.rb:242:in `configure'
	from /Users/denisahearn/development/sentera/CloudVault/config/initializers/airbrake.rb:4:in `<top (required)>'

It looks like this change in version 3.2.0 is what broke this: https://github.com/airbrake/airbrake-ruby/commit/7429844709cefeeef5837e98e36b13667694aa73#diff-ab40c6b5c07d8295ed2095faaad40369R14

More specifically:

    @git_version = Gem::Version.new(`git --version`.split.last)

The problem becomes obvious by looking at the output of the following commands:

```
14:07 ~/development/  $ git --version
git version 2.17.2 (Apple Git-113)

14:08 ~/development/  $ ruby -e 'puts `git --version`.split.last'
Git-113)
```

The following code isn't working based on way my Mac reports its git version

    `git --version`.split.last

Rolled back to version 3.1.0 for now.

**Comment by kyrylo** [comment]
Thanks for the bug report, I'm on High Sierra but for me `git --version` returns `git version 2.18.0`. I didn't realise there could be something else. The CI also didn't catch it.
