### ISSUE TITLE
the 'default' notifier was already configured (Airbrake::Error)

### ISSUE THREAD

**Issue by interestinall** [airbrake/airbrake-ruby#43]
Hey,

I'm new to airbrake. This is my config code:

```
Airbrake.configure do |config|
  config.project_key = 'xxxxxxx'
  config.project_id = xxxxxx
  config.ignore_environments = %w(development test)
end
```

Not sure how to fix this 'default' notifier was already configured error. Any advice would be appreciated.

**Comment by kyrylo** [comment]
Hey! What was the solution?

**Comment by interestinall** [comment]
I had two config files (one to push for others due to gitignore). Since it read both files, it was doing the config twice.

**Comment by kyrylo** [comment]
Awesome, thanks for the explanation :)
