### ISSUE TITLE
airbrake:deploy issue with airbrake-ruby (4.2.4) 

### ISSUE THREAD

**Issue by giovannelli** [airbrake/airbrake-ruby#471]
Hi there,
the **bundle exec cap airbrake:deploy** command fails after upgrading to airbrake-ruby (4.2.4)

```
bundle stdout: The Performance Stats feature is disabled
bundle stderr: Nothing written
```
I've forced **c.performance_stats = false** in airbrake.rb, but it doesn't seem to fix the issue.
Any thoughts?

Thank you in advance

**Comment by kyrylo** [comment]
Thanks, released a fix in 4.2.5.
