### ISSUE TITLE
Asynchronous notifier blocks if the queue is full

### ISSUE THREAD

**Issue by crunis** [airbrake/airbrake-ruby#48]
This https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/async_sender.rb#L27 will block if the queue is full.
I think blocking in an asynchronous component is completely unexpected, please consider merging https://github.com/airbrake/airbrake-ruby/pull/47

**Comment by kyrylo** [comment]
Fixed by #47.
