### ISSUE TITLE
Pause APM collection when the account is out of quota

### ISSUE THREAD

**Issue by kyrylo** [airbrake/airbrake-ruby#497]
Currently, the notifier keeps sending APM data when the account ran out of quota. This is rather wasteful because we reject that data immediately. We waste our own CPU cycles and users' bandwidth.

Instead, the notifier should be smart about it and pause APM collection when the account has no more quota. A 10-minute pause sounds reasonable. Once they get their new quota, in the worst case, they would need to wait only 10 minutes to see their APM data flowing to the dashboard.

The pause/continue event should be logged, so it's easier to debug issues with this feature.

**Comment by zefer** [comment]
Maybe we will want to revisit this if we have data suggesting it's a real problem, in the meantime my gut feeling is that it's adding complexity for a small optimisation but also adding a source of potential confusion both for users and us, when data is missing.
