### ISSUE TITLE
Ruby 2.7.0 (released version) warnings in tdigest.rb

### ISSUE THREAD

**Issue by BrianHawley** [airbrake/airbrake-ruby#536]
Warnings that look like this:
```
.../gems/airbrake-ruby-4.12.0/lib/airbrake-ruby/tdigest.rb:239: warning: rb_safe_level will be removed in Ruby 3.0
.../gems/airbrake-ruby-4.12.0/lib/airbrake-ruby/tdigest.rb:388: warning: rb_safe_level will be removed in Ruby 3.0
```
Coming out by the hundreds. Seen during test runs so far, because we're still upgrading and we don't have this version of airbrake in production yet.

**Comment by BrianHawley** [comment]
I tracked it down to the rbtree3 forked gem, in old code from before the fork. I made a PR to fix this issue, and all of the other issues I noticed while I was testing the fix: https://github.com/kyrylo/rbtree3/pull/7

**Comment by BrianHawley** [comment]
You might want to update your circleci image in ruby-2.7 mode to "circleci/ruby:2.7.0" so you can see the final deprecation messages. Update your rake development dependency too, to fix some deprecations that show up in the existing tests.

**Comment by kyrylo** [comment]
I released rbtree3 and [bumped](https://github.com/airbrake/airbrake-ruby/pull/541) the dependency in this project.
