### ISSUE TITLE
ThreadError: deadlock; recursive locking in Airbrake::PerformanceNotifier

### ISSUE THREAD

**Issue by matiasmelendi** [airbrake/airbrake-ruby#553]
I enabled performance monitoring in my production rails app and I'm getting a bunch of `ThreadError`.

I'm using `airbrake ~> 9.3.0` which depends on `airbrake-ruby -> 4.5.0`.
Rails version is `(~> 5.1.0)` running on ruby `2.5.5`...
Below is part of the stacktrace of the error:

```
/gems/airbrake-ruby-4.5.0/lib/airbrake-ruby/performance_notifier.rb:36 in synchronize
/gems/airbrake-ruby-4.5.0/lib/airbrake-ruby/performance_notifier.rb:36 in notify
/gems/airbrake-ruby-4.5.0/lib/airbrake-ruby.rb:358 in notify_request
/gems/airbrake-9.3.0/lib/airbrake/rails/action_controller_notify_subscriber.rb:17 in block in call
/gems/airbrake-9.3.0/lib/airbrake/rails/action_controller_notify_subscriber.rb:16 in each
/gems/airbrake-9.3.0/lib/airbrake/rails/action_controller_notify_subscriber.rb:16 in call
/gems/activesupport-5.1.6.2/lib/active_support/notifications/fanout.rb:127 in finish
```
Any clue on what could be causing the issue? None of the changes on newer versions seem to be related to thread management so I don't think that upgrading would solve it.

Thanks in advance!

**Comment by kyrylo** [comment]
Fixed by https://github.com/airbrake/airbrake-ruby/pull/554.
