### ISSUE TITLE
how to disable PerformanceNotifier in logs ? 

### ISSUE THREAD

**Issue by MathieuDerelle** [airbrake/airbrake-ruby#565]
after every http request, there's a huge amount of logs starting with
```
**Airbrake: Airbrake::PerformanceNotifier#send: 
```

That's a ton of useless information for me

It seems to be disable in env "production" 
but I'd like to disable it in all environments

**Comment by phumpal** [comment]
@MathieuDerelle might this work?

```
Airbrake.configure do |c|
  c.performance_stats = false
end
```

**Comment by thompiler** [comment]
@MathieuDerelle did you want to disable `PerformanceNotifier` events being logged or completely stop tracking all performance metrics?

**Comment by kyrylo** [comment]
We don't offer any special settings for disabling only those logs. It seems like your app sets `logger` level to `debug`, so that's why you see this debug output. Have you tried adjusting the severity level?

```rb
Airbrake.configure do |c|
  c.logger.level = Logger::WARN
end
```

We don't want to remove that information because it is useful for debugging.

**Comment by MathieuDerelle** [comment]
@phumpal I don't want to disable APM, just the log

My log level was actually at `debug` via env variables

I believe it is the default level in dev env
When developing some controllers (in dev env), the huge amount on information logged "for nothing" is annoying (flooding the console)

I'm sure it is useful for debugging for the author of this gem.
But, for me, it's getting in the way of the actual information I'm interested in (rails controller/params details)

```
Airbrake.configure do |c|
  c.logger.level = Logger::WARN
end
````
did not work for me


but
```
Airbrake.configure do |c|
  c.logger = Logger.new(File::NULL)
end
```
did

thanks !
