### ISSUE TITLE
Configuration setting for unhandled exceptions

### ISSUE THREAD

**Issue by ktimothy** [airbrake/airbrake-ruby#58]
Hey!

Currently airbrake-ruby notifies about unhandled errors, if they cause process exit, and there is no way to prevent airbrake from doing that. What if we add a config property, that will allow to turn off notifying on such exceptions?

**Comment by kyrylo** [comment]
Hey! It's hard to tell because at the moment it's not clear why it would be useful. What's your use case?

**Comment by ktimothy** [comment]
Well, I just think that this behavior is not obvious. I really thought, that this gem is developed for notifying airbrake with exceptions manually, not automatically.

**Comment by kyrylo** [comment]
I see your point and I think I agree with this. I'll transfer this behaviour to the airbrake gem instead as it makes more sense there.

Luckily, if you don't use the airbrake gem and only need this one, it's very easy to bring this behaviour back (literally 3 lines of code).

**Comment by ktimothy** [comment]
Nice!
