### ISSUE TITLE
How to remove exception classes from default ignore list?

### ISSUE THREAD

**Issue by jamesr2323** [airbrake/airbrake-ruby#593]
I've been trying to allow `ActionController::RoutingError` errors to be reported to Airbrake, as in my internal-facing application they are usually indicative of some larger issue. However I have not been able to do this. I can see that there is a remove_filter option but I'm unable to determine which class I should be removing. Any help would be greatly appreciated! I'm using `airbrake-ruby` 4.14.1 and `airbrake` 10.0.3 with `rails` 6.0.2.2. 

This is my `airbrake.rb`:

```
Airbrake.configure do |c|
  c.project_id = ENV['AIRBRAKE_PROJECT_ID']
  c.project_key = ENV['AIRBRAKE_PROJECT_KEY']

  c.root_directory = Rails.root
  c.logger = Airbrake::Rails.logger

  c.environment = Rails.env

  c.ignore_environments = %w[test]
  c.blacklist_keys = [/password/i, /authorization/i]
end
```

**Comment by kyrylo** [comment]
There's nothing to unignore because `ActionController::RoutingError` is not being raised by Rails. It is just being printed in the logs. In order to report 404's you need to:

1. Add a new "catch-all" route:
   
   ``` ruby
   # config/routes.rb
   match '*path', to: 'application#routing_error', via: [:get, :post]
   ```
2. Add a handler for routing errors, which raises a `RoutingError` manually:
   
   ``` ruby
   # app/controllers/application_controller.rb
   def routing_error
     raise ActionController::RoutingError,
           "No route matches [#{env['REQUEST_METHOD']}] #{env['PATH_INFO'].inspect}"
   end
   ```
