### ISSUE TITLE
Add GDPR infos about remote configuration

### ISSUE THREAD

**Issue by derSascha** [airbrake/airbrake-ruby#626]
Hi,

every company running this gem together with airbrake has actually a contract with airbrake, including all required things about the GDPR. The new remote config option introduced in 5.0 runs on every developer notebook as well and this requires some more GDPR information to the developers. Please add them to the readme and add a way to decline the data collection, otherwise its impossible to use this gem anymore inside the European Union.

Thanks

**Comment by destari** [comment]
Thanks for the comments!

Can you provide a bit more info on what you are expecting to see in our documentation? I am unclear on what exactly is missing, and how this is perhaps not already covered, so I want to be sure we are going the right direction from your point of view.

Also, the config feature is pulling a general config, by only using an HTTP GET request, and the only information that is passed (so we can correctly provide that configuration) are: notifier name and version, os, and language and version.  

This information is the same that is passed to our service when the notifier sends error information to us for your use.  The difference is that the config mechanism is designed so we can provide the correct configs without doing an HTTP POST or PUT, for example.

**Comment by derSascha** [comment]
Thanks for the response!

To be clear, there is a difference where you actually run the gem:

1. On production server: Its expected that data gets transmitted to airbrake and the customers of airbrake has signed contracts.
2. On CI servers / testing farm: not expected that any data gets transmitted
3. On developer notebooks: not expected that any data gets transmitted and no contract or GDPR things signed

I'm talking about the last point here, the developer notebook.

> Can you provide a bit more info on what you are expecting to see in our documentation? I am unclear on what exactly is missing, and how this is perhaps not already covered, so I want to be sure we are going the right direction from your point of view.

The usual GDPR stuff, see [Wikipedia](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) (in short: what data gets collected, why it gets collected, how the data gets processed, how the user can request a dump of its data and howto request a removal of its data)

> Also, the config feature is pulling a general config, by only using an HTTP GET request, and the only information that is passed (so we can correctly provide that configuration) are: notifier name and version, os, and language and version.

And project identifier and IP address of the client...

> This information is the same that is passed to our service when the notifier sends error information to us for your use. The difference is that the config mechanism is designed so we can provide the correct configs without doing an HTTP POST or PUT, for example.

Not sure why you talking about HTTP GET here, the HTTP method makes no difference to GDPR. As mentioned above, it is not expected that a development environment starts sending data. I have never seen such a behavior in a gem before. The developer system never send any error notification to airbrake.

**Comment by destari** [comment]
Yea, I agree on the non-production environment stuff.  We'll fix that up.  We are also reviewing some of the other needs, so stay tuned!
Thanks for the extra detail!

**Comment by kyrylo** [comment]
We added an option to disable the feature. It's documented here: https://github.com/airbrake/airbrake-ruby#remote_config

I hope this is enough to resolve this issue. Thanks for your help!

**Comment by derSascha** [comment]
@kyrylo thanks for finally merging [my suggested](https://github.com/airbrake/airbrake-ruby/pull/619) configuration option. I can't find anything about GDPR and you changed the default `remote_config` setting to `true`. I have no idea why this should change anything.

This does not change anything regarding the issue, please reopen! Thanks for your help!

**Comment by destari** [comment]
@derSascha  we don't typically add GDPR and other related information to the README as we have many places this would need to be managed, and so we follow a common practice of having our privacy policy, security documentation, and DPA cover those items, which can be found:

https://airbrake.io/docs/airbrake-faq/security/#does-airbrake-maintain-any-certifications-attestation-or-compliance

and:

https://airbrake.io/privacy

and the DPA can be requested by just emailing us (referenced on the above page), which should cover your needs.

**Comment by derSascha** [comment]
@destari I have never seen a gem with such an installation tracking feature before and I guess that's why you have never seen GDPR related information in a gem README. Actually, I'm not sure if this is enough or you need to show a banner about this at installation time to the user to be safe. Thanks for your help!
