### ISSUE TITLE
PerformanceNotifier outputting many logs when it should be disabled

### ISSUE THREAD

**Issue by stu-blair** [airbrake/airbrake-ruby#643]
I am running
* Airbrake version: airbrake gem 11.0.1, airbrake-ruby gem 5.2.0-java
* Ruby version: jruby 9.2.14.0
* Framework name & version: Rails 5.2.4.4

#### Airbrake config

```
Airbrake.configure do |c|
  c.performance_stats = false

  c.project_id  = << removed >>
  c.project_key = << removed >>

  c.root_directory = Rails.root

  c.logger = MyApp::Application.config.logger

  c.environment = AppConfig.airbrake_environment_name

  c.app_version = APPLICATION_VERSION.branch_name

  c.versions = {
    'Rails': Rails.version,
    'Pretty version': AppConfig.release_number
  }

  c.ignore_environments = %w[test]

  c.blocklist_keys = [/password/i, /authorization/i]
end

```

#### Description

I have `performance_stats=false` in `airbrake.rb`, but I am seeing tons of logs from performance notifier, so it seems like it's still running.

For example, here from the rails console, I can confirm the config is correctly disabled, but I still see performance notifier output when logger is set to debug:
```
> Airbrake::Config.instance.performance_stats
 => false
> quit()
"**Airbrake: thread pool closed"
"**Airbrake: thread pool closed"
"**Airbrake: performance notifier closed"
```

Not sure if this is related, but I also see this outputted over and over every 20 minutes in the logs, which I didn't see on previous airbrake (recently upgraded from 9.2.0 to 11.0.1):
```
"**Airbrake: applying remote settings: {\"project_id\"=>1234, \"updated_at\"=>1595827141, \"poll_sec\"=>0, \"config_route\"=>\"2020-06-18/config/1234/config.json\", \"settings\"=>[]}"
```

**Comment by scottsbaldwin** [comment]
Thanks @stu-blair, we'll take a look.

**Comment by stu-blair** [comment]
Many thanks @scottsbaldwin and @kyrylo , I eagerly await your thoughts !

I should also mention I was already using NewRelic for performance monitoring, and ever since upgrading Airbrake, when starting the app, I see a StackOverflowException that includes paths from both the newrelic and airbrake gem (though it recovers and then seems to run OK). My theory is that this is also caused by the airbrake performance notifier running (even though it should be disabled), and that the two performance monitors are interfering with one another.

**Comment by stu-blair** [comment]
I think I have another clue-- airbrake is running even if I do not configure it at all! Meaning, if I delete the initializer that sets up airbrake, so `Airbrake.configure` is not called whatsoever, I still find that some kind of Airbrake instance is running, with `performance_stats` set to true.

```
> Airbrake.configured?
 => false
jruby-9.2.14.0 :004 > Airbrake::Config.instance
 => #<Airbrake::Config:0x50d8b30 @project_id=nil, @code_hunks=true, @query_stats=true, @job_stats=true, @workers=1, @project_key=nil, @versions={}, @performance_stats=true, @error_notifications=true, @queue_size=100, @timeout=nil, @host="https://api.airbrake.io", @allowlist_keys=[], @root_directory="<< removed >>", @ignore_environments=[], @blocklist_keys=[], @performance_stats_flush_period=15, @logger=#<Logger:0x48e7e2ca @level=2, @logdev=#<Logger::LogDevice:0x1b557402 @shift_age=0, @shift_period_suffix="%Y%m%d", @filename="/dev/null", @dev=#<File:/dev/null>, @mon_mutex=#<Thread::Mutex:0x71a2a9a0>, @shift_size=1048576, @mon_owner=nil, @mon_count=0>, @default_formatter=#<Logger::Formatter:0x189fe8af @datetime_format=nil>, @progname=nil, @formatter=nil>, @remote_config=true, @remote_config_host="https://notifier-configs.airbrake.io", @apm_host="https://api.airbrake.io", @proxy={}>
```

**Comment by stu-blair** [comment]
Maybe related to
https://github.com/airbrake/airbrake/issues/546
https://github.com/airbrake/airbrake-ruby/pull/75

Though the real issue isn't that airbrake runs when the gem is required, even if its not configured (I could probably fix that by making sure the gem doesn't get required if it should be disabled), the real problem is that when it is enabled and `performance_stats=false`, some kind of performance monitoring process is still being run

**Comment by stu-blair** [comment]
One more note-- I downgraded airbrake to `9.5.5` and these issues went away

**Comment by kyrylo** [comment]
Hey @stu-blair! 

> Not sure if this is related, but I also see this outputted over and over every 20 minutes in the logs, which I didn't see on previous airbrake (recently upgraded from 9.2.0 to 11.0.1):

This is intentional and we document it here: https://github.com/airbrake/airbrake-ruby#remote-configuration
It's indeed a new feature. Basically, you will be able to change notifier settings without restarting your app. We currently don't provide means to do that but that's planned in the future.

> I have performance_stats=false in airbrake.rb, but I am seeing tons of logs from performance notifier, so it seems like it's still running.

Can you please email me your project id? kyrylo@airbrake.io
That is unexpected, but maybe the remote configuration feature gets in the way.

> I noticed that if Airbrake.configure is not called at all, but the gem is required, I find that some kind of Airbrake instance is running, with performance_stats=true

Performance stats are enabled by default, so it's expected that something is running when you don't call `configure`.

So the logs that you see, do they start like this? `DEBUG -- : **Airbrake: Airbrake::PerformanceNotifier#send`

If that's the case, then indeed performance stats are not disabled.

**Comment by stu-blair** [comment]
Thank you for the helpful explanations. Emailed my project ID in case it helps. I ended up sticking with `v9.5.5` to avoid this issue.

**Comment by kyrylo** [comment]
Thanks! I checked your project, and I couldn't spot anything weird.

I tweaked the logger messages that you posted in your original message, so that they're more clear. That said, the performance notifier starts despite the value of `performance_stats`. When it's `false`, it will be no-op (won't do anything). In the future you would be able to turn on performance stats without restarting your app (without setting `performance_stats` to true).

So the logs that you see, do they start like this? `DEBUG -- : **Airbrake: Airbrake::PerformanceNotifier#send`. If you see those kind of logs, then it's not normal. If you see only the messages that you posted, then it's normal.

**Comment by kyrylo** [comment]
Closing for now. Please let me know if this is still an issue for you. I have a hunch that it works as expected but some log output that you saw confused you. Either way, feel free to ping me.

**Comment by Liboul** [comment]
FWIW, we got rid of the logs by setting the `remote_config` config attribute to false in ignored environments. Maybe this could be a nicer default?

```rb
Airbrake.configure do |c|
  c.ignore_environments = ... # Our own config here
  c.remote_config = false # if ignored environement
end
```

**Comment by kyrylo** [comment]
@Liboul do you see the logs in production? Could you describe the scenario when you see them?

**Comment by Liboul** [comment]
I have them in development mode even though development is part of the `ignored_environments`:

![image](https://user-images.githubusercontent.com/16024169/113120345-c7da3d80-9211-11eb-90f6-239ec13b5252.png)

I also see them when accessing the console on Heroku:

![image](https://user-images.githubusercontent.com/16024169/113120435-e04a5800-9211-11eb-9d54-e1f05011f0b1.png)

It's not critical at all, just a bit annoying
