### ISSUE TITLE
Clarify the impact of disabling the `remote_config` feature

### ISSUE THREAD

**Issue by pouellet** [airbrake/airbrake-ruby#645]
The [documentation](https://github.com/airbrake/airbrake-ruby#remote_config) for the remote config has the following note: 

> Note: it is not recommended to disable this feature. It might negatively impact how your notifier works. Please use this option with caution.

This warning is a bit nebulous and doesn't really say much about what will be impacted when `remote_config` is disabled. I can understand why some customers might want the flexibility to update their configuration from the Airbrake UI, but I think that having the configuration statically defined in our source repo is also a valid and common workflow. Providing more information on what is actually impacted by this setting would allow Airbrake users to make a better informed decision on  whether or not to disable it.

As an aside, did you consider using the `ignore_environments` setting to automatically disable the `remote_config` instead of hardcoding it to check for `test`?

Thanks!

**Comment by scottsbaldwin** [comment]
@pouellet thanks for your suggestion. I have created an issue on our internal development backlog (and close this issue) to include a better explanation for the `remote_config` feature in future updates of our docs.

We didn't consider using `ignore_environments`. I'll check with the team to see if that's an improvement we can pick up.

**Comment by pouellet** [comment]
@scottsbaldwin in the meantime, do you know if there is any harm in disabling it? Will it affect the notifier in a significant way?

**Comment by scottsbaldwin** [comment]
@pouellet as of right now, it will not affect you negatively if you disable it.
