### ISSUE TITLE
Is Airbrake.merge_context thread safe?

### ISSUE THREAD

**Issue by sjain** [airbrake/airbrake-ruby#658]
We are using Airbrake with shoryuken gem. We have noticed atleast one instance where the airbrake reported context is different from the one where error occured. Upon closer look, I find that we are relying on `Airbrake.merge_context` to setup the context before we process each shoryuken request. We are calling `Airbrake.notify` when error/exception occurs, which as I understand, is an async call by default.

Perusing the gem code seems to suggest that `Airbrake.notify` does the right thing of storing the context inside Notifier for async notification to pickup. However, I don't see any Thread.current in the call chain from Airbrake to NoticeNotifier etc. I wonder if this Airbrake code is threadsafe?

This documentation does not make it explicit: https://github.com/airbrake/airbrake-ruby#airbrakemerge_context

**Comment by scottsbaldwin** [comment]
@kyrylo can you take a look at this?
