### ISSUE TITLE
Its possible to log the output of all promises?

### ISSUE THREAD

**Issue by neohunter** [airbrake/airbrake-ruby#662]
Hello, I would like to log the result of all notify actions.

```ruby
Airbrake.notify('Oops').then { |response| Rails.logger.info "Airbrake result #{response}"}
```

Is there an implemented way to do something like that? I was thinking in do some monkey patching like:

```ruby
class Airbrake
  alias_method :old_notify, :notify
  def notify(...)
     promise = old_notify(...)
     promise.then do |response|
        Rails.logger.info "Airbrake result #{response}"
     end
     promise
  end
end
```

**Comment by scottsbaldwin** [comment]
@neohunter have you looked at using `Airbrake.notify_sync` instead? See https://github.com/airbrake/airbrake-ruby#airbrakenotify_sync.

**Comment by kyrylo** [comment]
I noticed you use Rails. The airbrake gem already logs results in `log/airbrake.log` (for all HTTP calls).

**Comment by kyrylo** [comment]
@neohunter let me know if you meant to ask something else. Maybe you could describe your use case?

**Comment by neohunter** [comment]
> I noticed you use Rails. The airbrake gem already logs results in log/airbrake.log (for all HTTP calls).

How can I output that to STDOUT instead? 

The problem we have is that we collect logs using datadog, we only collect the output of STDOUT, we would like to add to the logs the url to locate the error on airbrake when new error is created, so we can track bugs easier on logs / airbrake.

I tried with my monkey patch but it's not working.

`notify_sync` is a good option but have 2 problems:

1) Is sync
2) I would need to change all places where `Airbrake.notify` is used, which I do not want.

**Comment by kyrylo** [comment]
Have you tried setting the `RAILS_LOG_TO_STDOUT` env variable?
