### ISSUE TITLE
Remote configuration is polled for despite `ignore_environments`

### ISSUE THREAD

**Issue by ghiculescu** [airbrake/airbrake-ruby#679]
```ruby
Airbrake.configure do |c|
  c.environment = "development" # Rails.env
  c.ignore_environments = ["development", "test"]
end
```

If you open a Rails console or Rails server and use a gem like https://github.com/martinbtt/net-http-spy you will periodically see requests like this:

```
starting SSL for notifier-configs.airbrake.io:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "GET /2020-06-18/config/116296/config.json
```

I see that since https://github.com/airbrake/airbrake-ruby/pull/636 you can set `remote_config: false` but then it doesn't work anywhere, or you can do something like `remote_config: ["development", "test"].include?(Rails.env.to_s)` but then you're duplicating config. Either way the readme vaguely advises against this - "it is not recommended to disable this feature. It might negatively impact how your notifier works. Please use this option with caution.".

Would you accept a PR that changes https://github.com/airbrake/airbrake-ruby/blob/dfd766fc688c55741e3e8b98fa5ac7ba1fbc4c48/lib/airbrake-ruby/config/processor.rb#L46 to instead check `ignore_environments`?

(If no that's fine, I figure logging this here will help anyone else who gets confused by this :))

**Comment by kyrylo** [comment]
Let's keep `test` hardcoded there. In 100% of cases, we don't want that call to happen while people test their libraries. By default, `ignore_environments` is empty, and therefore it might force everyone to configure it just because of this pesky HTTP call. I would accept a PR that takes ignore environments into account but also keeps `test` there.
