### ISSUE TITLE
Airbrake.notify doesn't accept a string as a param

### ISSUE THREAD

**Issue by hajder** [airbrake/airbrake-ruby#68]
Documentation states that I can just pass a string as a param to `Airbrake.notify` but when I do I get an empty `Notification` in Airbrake (it has no message, etc).

Should be updated to correctly state that a hash should be passed with i.e. `error_message: 'App crashed!'`

**Comment by kyrylo** [comment]
Hey @hajder! What is your Airbrake version? Airbrake v4 doesn't support that API, it's an Airbrake v5 feature.

**Comment by hajder** [comment]
Yes, I guess you're right!
