### ISSUE TITLE
send_notice raises URI::InvalidURIError with invalid URIs

### ISSUE THREAD

**Issue by jdelStrother** [airbrake/airbrake-ruby#69]
If a user visits a badly formed URI (say, http://example.com/foo]bar), and the app raises an exception (perhaps because of the badly formed URI), the airbrake gem will raise a second exception while trying to parse `notice[:context][:url]`, which prevents the original error from reaching Airbrake.   Here's a partial stack from such an error:

```
/Users/jon/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/common.rb, line 747
/Users/jon/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/common.rb, line 1232
airbrake-ruby (1.1.0) lib/airbrake-ruby/filters/keys_filter.rb, line 32
airbrake-ruby (1.1.0) lib/airbrake-ruby/filter_chain.rb, line 64
airbrake-ruby (1.1.0) lib/airbrake-ruby/filter_chain.rb, line 62
airbrake-ruby (1.1.0) lib/airbrake-ruby/notifier.rb, line 123
airbrake-ruby (1.1.0) lib/airbrake-ruby/notifier.rb, line 45
airbrake-ruby (1.1.0) lib/airbrake-ruby.rb, line 282
airbrake-ruby (1.1.0) lib/airbrake-ruby.rb, line 136
airbrake (5.1.0) lib/airbrake/rack/middleware.rb, line 39
```

Perhaps `KeysFilter#call` should catch URI::InvalidURIError and quietly return?   Or replace `notice[:context][:url]` with `"<invalid URI>"` ?

**Comment by kyrylo** [comment]
Thanks for the report! I think we should not hide the URL behind `<invalid URL>` and try to encode it, so it is similar to the behaviour in [your past PR](https://github.com/airbrake/airbrake-ruby/pull/45). Wanna tackle this?

**Comment by jdelStrother** [comment]
Ugh, I knew I'd reported something similar before but couldn't find it.   Yeah, will try & come up with another PR.

**Comment by kyrylo** [comment]
I had to fix this myself because I stumbled upon this bug myself :) https://github.com/airbrake/airbrake-ruby/issues/70
