### ISSUE TITLE
Performance monitoring scope/features

### ISSUE THREAD

**Issue by misner** [airbrake/airbrake-ruby#692]
I'm trying to understand the scope of the Performance monitoring's component of Airbrake: For a ruby on rails project, we're wondering if we could replace our current APM solution with yours alongside airbrake Error monitoring, unifying & simplifying our stack

The main way we use APM is to identify database n+1 requests in production as well as check memory allocation, bloat or leaks.
I could not find docs about how you surface all those via specific alert and metrics. Could you point me to the right direction? 

Many thanks.

**Comment by kyrylo** [comment]
Hey Mike!

Airbrake APM for RoR offers a way to monitor your routes, queries, and jobs. You will be able to compare routes' response codes, response times, and some other stats with each other. Each route provides more granular data, such as Apdex score and response time breakdown (a rough outline of where your route spends time; e.g., database, view rendering, and such; you can also define your own breakdowns). The Route view will help you understand what queries were executed when that route was hit. The Query view provides a general overview of the queries your app makes. The same goes for jobs. We measure all metrics' performance and provide 50th and 90th percentile response time. You will be able to identify slow queries.

At the moment, we do not check for memory bloat or leaks. Could you help me understand how your current APM solution is good at the N+1 query problem?

You may want to try to use https://github.com/flyerhzm/bullet to remedy the N+1 query problem. I've never tried this gem myself, but I know it exists.
