### ISSUE TITLE
sanitize_hash in KeysFilter may leak sensitive blocklisted params

### ISSUE THREAD

**Issue by micred** [airbrake/airbrake-ruby#704]
* Airbrake version: 6.2.0
* Ruby version: 3.1.0
* Framework name & version: Rails 7.0.2.3

#### Airbrake config
```
Airbrake.configure do |config|
  config.blocklist_keys = [:password]
end
```
#### Description
I trigger this notification:
```
Airbrake.notify('test',
   password: 'p',
   nested: {
     password: 'p'
   },
   openstruct: OpenStruct.new({password: 'p'}),
   params: ActionController::Parameters.new(password: 'p'), # Rails
   record: User.first, # Rails
   relation: User.all  # Rails
)
```

I expected to have the passwords filtered in any object, but only the first two were filtered.

I know that the user should cast the data to hash _before_ calling Airbrake.notify, but it is allowed to the user (no deep check on the values inside the hash, that may not be hash themself).
It leads to very dangerous sensitive data leaks of blocklisted attributes (like passwords in plain text).

**Comment by kyrylo** [comment]
Hi, @micred! Thanks for opening this issue.

> I expected to have the passwords filtered in any object,

Where does this expectation come from? Do other error tracking tools do that?

> I know that the user should cast the data to hash before calling Airbrake.notify

From what I remember, I think our docs don't make this clear. But the behavior you demonstrated serves as proof of your statement. I think we should make this clearer in the docs as well.

**Comment by micred** [comment]
> Where does this expectation come from? Do other error tracking tools do?

This expectation comes from the README:
> blocklist_keys - Specifies which keys in the payload (parameters, session data, environment data, etc) should be filtered.

Ok, no worries if you don't want to merge the PR, makes sense.
