### ISSUE TITLE
6.2.1-java missing on rubygems.org

### ISSUE THREAD

**Issue by nicholasdower** [airbrake/airbrake-ruby#718]
Dear Airbrake Ruby folks,

I am having trouble updating to 6.2.1 because the java version is not available on rubygems.org. Could you please tell me whether you intend to release a java version for 6.2.1?

https://rubygems.org/gems/airbrake-ruby/versions/6.2.0 (works)
https://rubygems.org/gems/airbrake-ruby/versions/6.2.0-java (works)
https://rubygems.org/gems/airbrake-ruby/versions/6.2.1 (works)
https://rubygems.org/gems/airbrake-ruby/versions/6.2.1-java (missing)

FYI, I found a possibly related change from @kyrylo: https://github.com/airbrake/airbrake-ruby/commit/ce7793a34f268ac7c28b7dd5ecea591e8d7e0db6

Any assistance you can provide would be greatly appreciated.

**Comment by klobuczek** [comment]
My understanding is that whenever a platform-specific flavor of a gem is required (.i.e java) that version should be deployed first otherwise jruby might be pulling the gem meant for MRI. Therefore 6.2.1 shouldn't have been released before 6.2.1-java.

**Comment by kyrylo** [comment]
@mmcdaris @thompiler there's the `pushgems` task that I used to use to release this gem: https://github.com/airbrake/airbrake-ruby/blob/f2cc9917a18004330d17a05c7ab4f84c1ea2ce02/Rakefile#L48-L53

It builds the gem both for JRuby and CRuby.

**Comment by klobuczek** [comment]
@mmcdaris @thompiler @kyrylo can anyone help with that?
