### ISSUE TITLE
Airbrake::Error: the 'default' notifier isn't configured" thrown when an error occurs in a sidekiq job while running tests

### ISSUE THREAD

**Issue by ToadJamb** [airbrake/airbrake-ruby#72]
We have some Sidekiq jobs in a Rails project and this is the error message we see when an error occurs INSIDE a job during testing. Errors inside of the spec itself work correctly.

``` ruby
# my_job.rb
class MyJob < ActiveJob::Base
  queue_as :default
  def perform(id)
    1 / 0
  end
end
```

``` ruby
# spec/support/sidekiq.rb
require 'sidekiq/testing'
Sidekiq::Logging.logger = nil
Sidekiq::Testing.inline!
```

``` ruby
# spec/my_job_spec.rb
RSpec.describe MyJob do
  it 'fails as expected' do
    1 / 0 #=> RSpec displays ZeroDivisionError
  end

  it 'does not fail as expected' do
    MyJob.perform_later 1 #=> Airbrake::Error (the real error is completely hidden)
  end
end
```

**Comment by ToadJamb** [comment]
This is a non-issue. Unfortunately, I was missing looking at a key part of our initialization process that was causing the `Airbrake.configure` block to be skipped altogether in higher environments.

**Comment by kyrylo** [comment]
Glad that you were able to resolve it. Happy Airbraking!
