### ISSUE TITLE
Airbrake being run on test and development environments

### ISSUE THREAD

**Issue by Reinkaos** [airbrake/airbrake-ruby#91]
Hey, 

My team is experiencing a problem with the new version of Airbrake. We are receiving error messages from our development and test environments even though we have
 config.ignore_environments = %w(development test)
in our config block.

Please advise what we may have done wrong :).

Richard

**Comment by kyrylo** [comment]
Hey, @Reinkaos. Please share exact version of airbrake-ruby and your full config.

**Comment by Reinkaos** [comment]
Hey thanks for your our quick reply,

Our airbrake-ruby version is 1.3.1 and here is our full config

Airbrake.configure do |config|
  config.project_key = KEY
  config.project_id = ID
  config.ignore_environments = %w(development test)
end

**Comment by kyrylo** [comment]
Thanks! Latest version of the library is 1.4.1 (it was released a few days ago).

Your problem is that you don't specify environment, so the library doesn't know what to do with `%w(development test)`.

Here's how you could fix the issue:

```rb
Airbrake.configure do |config|
  config.project_key = KEY
  config.project_id = ID
  config.environment = 'production' # <--------------- If you use Rails, set this to `Rails.env`
  config.ignore_environments = %w(development test)
end
```

**Comment by Reinkaos** [comment]
Great thanks for that, I will do that :).

**Comment by kyrylo** [comment]
One gotcha: be sure that types of your environments match. If you use Strings for `ignore_environments`, then use a String for `environment`, too.

**Comment by Reinkaos** [comment]
Right, so if I use Rails.env would they be strings?

**Comment by kyrylo** [comment]
Yeah.

**Comment by Reinkaos** [comment]
Awesome thank you :)

**Comment by kyrylo** [comment]
Now we print a warning if this situation happens, so I hope this won't cause any confusion in the future. Thanks for the report!
