### ISSUE TITLE
Default ignored errors

### ISSUE THREAD

**Issue by dsandstrom** [airbrake/airbrake-ruby#96]
Does Airbrake v5.4 have any [default ignored errors](https://github.com/airbrake/airbrake/wiki/Customizing-your-airbrake.rb#ignoring-errors-certain-types-of-errors)?  I think I know the answer to this already, but just want to confirm.

**Comment by kyrylo** [comment]
Thanks for the question. The library ignores only `SystemExit`.

**Comment by dsandstrom** [comment]
Has Airbrake thought about making an airbrake-rails gem to add some Rails specific configuration as default.  Like the default ignored errors and adding:
```
config.environment = Rails.env
config.ignore_environments = %w(test development)
```
It would save time in configuring apps and minimize confusion when updating.

**Comment by kyrylo** [comment]
We actually do that with our Rails initialiser: https://github.com/airbrake/airbrake/blob/master/lib/generators/airbrake_initializer.rb.erb

If you update, you have to configure it manually (or just `rm` the old config and generate a new one).

**Comment by dsandstrom** [comment]
Cool, thanks for the heads up.  I'm using the configs that Errbit suggests, which seems to be incomplete.
