### ISSUE TITLE
Airbrake throws away information for incompatible backtraces

### ISSUE THREAD

**Issue by martinvium** [airbrake/airbrake-ruby#98]
Hi,

This pull request (from what i gather) introduces a new method of parsing backtraces:

https://github.com/airbrake/airbrake-ruby/pull/4

However it errors out early when it fails to parse, throwing away the rest of the backtrace:

    raise Airbrake::Error, "can't parse '#{stackframe}'"

In my case an Oracle stored procedure call might fail, their errors are incompatible with your parser, but instead of printing the whole thing, only the last item is returned:

    Airbrake::Error (can't parse 'stmt.c:243:in oci8lib_220.so')

Example of the full "backtrace"/error message:

    OCIError: ORA-02291: integrity constraint (STORE.SN_PACE_REGISTRATIONS_FK01) violated - parent key not found
    ORA-06512: at "STORE.LI_LICENSES_PACK", line 1945
    ORA-06512: at "ACTIVATION.LI_ACT_LICENSES_PACK", line 101
    ORA-06512: at line 2
    from stmt.c:243:in oci8lib_220.bundle

Downgrading to 4.3.8 resolves the problem for me giving me:

    ORA-02291: integrity constraint (STORE.SN_PACE_REGISTRATIONS_FK01) violated - parent key not found ORA-06512: at "STORE.LI_LICENSES_PACK", line 1945 ORA-06512: at "ACTIVATION.LI_ACT_LICENSES_PACK", line 101 ORA-06512: at line 2

Note: This not only breaks airbrake integration, but hides error messages in both development mode webview and log files.

* Airbrake version: 5.4.0
* Ruby version: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
* Framework name & version: rails (4.2.6), ruby-oci8 (2.2.2), ruby-plsql (0.6.0)

**Comment by martinvium** [comment]
My suggestion would be to not raise in these cases, but return a dummy hash, something like:

    { file: nil, line: nil, function: stackframe }

**Comment by kyrylo** [comment]
Hey there @martinvium! 
Thanks for the report. I think we should try to parse it since it contains line numbers useful for grouping and the format seems to be well-defined. When the library raises, it prints what it can't parse, so it helps adding support for new backtrace formats.

**Comment by martinvium** [comment]
Completely up to you if you want to support Oracle directly, that would be great. Even then, i think there should be a reasonable fallback, since you might not know what other types of formats might exist out there and it's really hard to debug (until you know what the problem is).

**Comment by kyrylo** [comment]
True, but if we don't raise, how would we know we don't support something? :)

**Comment by martinvium** [comment]
You could flag it in the notice? raw_backtrace: true

**Comment by martinvium** [comment]
Really it was painful to debug, and took me a while to realize it was a general problem and not just a special case, then figure out that it was not a problem with either of the Oracle gems, then on the various other middleware, until Google told me about above PR, which i eventually realized was triggering the behaviour (in between lots of trial and error to see what the "true" output was of manually triggering the stored procedure).

**Comment by kyrylo** [comment]
I'd like to clarify: was it hard to find the root of the error because of the confusing error message or because of the nature of stored procedures (that is, you didn't have access or couldn't see the error in the first place)?

**Comment by martinvium** [comment]
It was hard to debug the original problem, because Airbrake only showed the last (and really not relevant) line of the error:

    from stmt.c:243:in oci8lib_220.bundle

Hiding all the interesting stuff:

    OCIError: ORA-02291: integrity constraint (STORE.SN_PACE_REGISTRATIONS_FK01) violated - parent key not found
    ORA-06512: at "STORE.LI_LICENSES_PACK", line 1945
    ORA-06512: at "ACTIVATION.LI_ACT_LICENSES_PACK", line 101
    ORA-06512: at line 2

It was _also_ hard to figure out that Airbrake was at "fault", and that i needed to downgrade to fix it.

**Comment by martinvium** [comment]
Also the entire backtrace was obfuscated, because this is an "error" in Airbrake, i don't see the original stacktrace e.g. which controller was triggering it, only the Airbrake middleware backtrace.

**Comment by kyrylo** [comment]
Thanks for the bug report again and your feedback! Now the library won't crash on unsupported stack frames and log them instead.

**Comment by martinvium** [comment]
Thank you very much for the quick response and fix! Much appreciated, will give it a spin next week.
